# Generated by Django 5.1.2 on 2024-10-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='dietitian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
