# Generated by Django 5.1.2 on 2024-10-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0009_alter_availability_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='day',
            new_name='available_days',
        ),
    ]
