# Generated by Django 5.1.2 on 2024-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0011_nutritionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
