# Generated by Django 5.1.2 on 2024-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0003_dietitian_profile_user_profile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
