# Generated by Django 5.1.2 on 2024-10-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0005_alter_user_profile_gender_alter_user_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitian_profile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
