# Generated by Django 5.1.2 on 2024-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0006_alter_dietitian_profile_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('dietitian', 'DIETITIAN'), ('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=100),
        ),
    ]
