# Generated by Django 5.1.2 on 2024-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0008_alter_dietitian_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitian_profile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
