# Generated by Django 5.1.2 on 2024-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0009_dietitian_profile_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitian_profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
