# Generated by Django 5.1.2 on 2024-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0011_alter_dietitian_profile_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitian_profile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='dietitian_certificates'),
        ),
    ]
