# Generated by Django 5.1.2 on 2024-10-29 15:13

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0012_alter_dietitian_profile_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitian_profile',
            name='specialties',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('General Nutrition', 'General Nutrition'), ('Weight Management', 'Weight Management'), ('Sports Nutrition', 'Sports Nutrition'), ('Diabetes Management', 'Diabetes Management')], max_length=200),
        ),
    ]
