# Generated by Django 5.1.2 on 2024-10-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0014_alter_dietitian_profile_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitian_profile',
            name='specialties',
            field=models.TextField(blank=True),
        ),
    ]
