# Generated by Django 5.1.2 on 2024-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0015_alter_dietitian_profile_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitian_profile',
            name='specialties',
            field=models.CharField(blank=True, choices=[('General Nutrition', 'General Nutrition'), ('Weight Management', 'Weight Management'), ('Sports Nutrition', 'Sports Nutrition'), ('Diabetes Management', 'Diabetes Management')], max_length=200),
        ),
    ]
