# Generated by Django 5.1.2 on 2024-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
        ('users_account', '0016_alter_dietitian_profile_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='chronic_condition',
            field=models.ManyToManyField(to='admin_side.chronic_conditions'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dietary_goal',
            field=models.ManyToManyField(to='admin_side.specialties'),
        ),
        migrations.RemoveField(
            model_name='dietitian_profile',
            name='specialties',
        ),
        migrations.AddField(
            model_name='dietitian_profile',
            name='specialties',
            field=models.ManyToManyField(to='admin_side.specialties'),
        ),
    ]
