# Generated by Django 5.1.2 on 2024-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0017_user_profile_chronic_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='cholestrol_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='suger_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
